### ISSUE TITLE
inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by LogX7** [jcupitt/rtiacquire#15]
this is what i get when i run `RTIAcquire`

```
Traceback (most recent call last):
  File "/usr/local/bin/RTIAcquire", line 10, in <module>
    import rtiacquire.rtiacquire
  File "/usr/local/lib/python3.6/dist-packages/rtiacquire/rtiacquire.py", line 225
    self.camera.release()
                        ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by jcupitt** [comment]
Huh weird. Thanks for reporting this!
